### PR TITLE
Review PR for latest htmldumper

### PR DESCRIPTION
**Pull request by gwicke**
This is a review from master to a branch, so that we have a PR for review purposes.

### CODE REVIEW

**Comment by d00rman** [comment]
I have reviewed the code before and it still looks good (even better than last time) :+1: 

Nitpick: state in the docs `pixz` is used for (de)compression to avoid surprises at the end of the dump process ;)

**Comment by gwicke** [comment]
> Nitpick: state in the docs pixz is used for (de)compression to avoid surprises at the end of the dump process ;)

Good catch. Addressed in a691da7e8b66531.

**Comment by eevans** [comment]
LGTM; :+1:

**Pull request closed without merging**
